### ISSUE TITLE
Android Build

### ISSUE THREAD

**Issue by vinodshinde** [logandk/restful_mapper#5]
Hi,
Is it possible to build this library for Android using Android Studio 2.2 and CMake?

I am new to C++, so any help will be great.

Thanks,
Vinod

**Comment by logandk** [comment]
Hi Vinod,
Assuming you have the dependencies (curl, yajl and iconv) available on your system, it should be a simple matter of adding the CMake build step to your Gradle project: https://developer.android.com/ndk/guides/cmake.html

I do not have the time or need to try this out for myself at the moment, but I don't see any reason why it shouldn't work as expected.

I'm closing this ticket as it is not directly related to any bugs or features in the library.
